### ISSUE TITLE
Remove "immutable" go-bindata conveniences

### ISSUE THREAD

**Issue by jackfrancis** [deis/docker-go-dev#121]
Wonder if anyone else is having similar issues. @tariq1890 has a change in Azure/acs-engine here that statically pins a go-bindata version to a particular repo to avoid downstream changes conflicting:

https://github.com/Azure/acs-engine/pull/3527

Basically, should we remove the `go get` convenience from this image and require each use case deliver their own, opinionated (and specific) version?

Thoughts?

**Comment by mboersma** [comment]
docker-go-dev is strictly in maintenance mode, and I don't think we should change anything WRT go-bindata at this point. ☮️  and ❤️  to you and Tariq!
