### ISSUE TITLE
deploy.sh should use *_USERNAME env vars

### ISSUE THREAD

**Issue by mboersma** [deis/docker-go-dev#23]
All other versions of `deploy.sh` are standardized on `QUAY_USERNAME` and `DOCKER_USERNAME`, so this script should be updated.

See also deis/docker-python-dev#8.

**Comment by Joshua-Anderson** [comment]
So you want to rename `$QUAY_USER` -> `$QUAY_USERNAME`?

**Comment by mboersma** [comment]
This issue is ancient and not relevant now.
