### ISSUE TITLE
Migrate from Travis

### ISSUE THREAD

**Issue by sozercan** [deis/docker-go-dev#259]
`Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.`

Might need to migrate PRs from Travis

**Comment by mboersma** [comment]
I've checked out travis-ci.com but there are some issues migrating this deis repository over there, not to mention that things aren't perpetually free any longer. I think the best approach might be to augment the Azure Pipelines MCR job to also publish back to Docker Hub and quay.io (if that doesn't raise any issues for us).

**Comment by mboersma** [comment]
Closed by #266.
