### ISSUE TITLE
Use go-delve/delve instead of derekparker/delve 

### ISSUE THREAD

**Issue by Cryptophobia** [deis/docker-go-dev#265]
https://github.com/deis/docker-go-dev/blob/637224b6909bf36b7cd8224a368964630d6a93f2/rootfs/Dockerfile#L97

Hey @mboersma, any reason why this is still calling `derekparker/delve`?

It is 168 commits behind official https://github.com/go-delve/delve

**Comment by mboersma** [comment]
> any reason why this is still calling derekparker/delve?

Just old code that never got looked at again. I will update it--thank you for noticing!
