### ISSUE TITLE
when will golang 1.16 image be created?

### ISSUE THREAD

**Issue by andyliuliming** [deis/docker-go-dev#277]
:)

**Comment by andyliuliming** [comment]
@mboersma  @sozercan  :)

**Comment by mboersma** [comment]
@andyliuliming I tried this a couple weeks ago and of course ran into compilation-related errors, but didn't follow up. I'll try to revisit it today or tomorrow and see if I can fix it and do a new release.

**Comment by mboersma** [comment]
@andyliuliming docker-go-dev:[v1.31.0](https://github.com/deis/docker-go-dev/releases/tag/v1.31.0) has go v1.16.3 in it. Thanks for the nudge!

**Comment by andyliuliming** [comment]
@mboersma  thanks very much!
