### ISSUE TITLE
rename repository to simpler "go-dev"

### ISSUE THREAD

**Issue by mboersma** [deis/docker-go-dev#40]
It's just confusing to have the repo `deis/docker-go-dev` produce the docker image `quay.io/deis/go-dev`, and I would argue prepending "docker" is either redundant or packaging-specific.

**Comment by krancour** [comment]
I was responsible for that decision when I incepted this repo.  I'll share my rationale, in case it resonates with you.  If not, I wouldn't fight you on this...

Including "docker" in the image name would have been redundant (as you pointed out).  _Everything_ in Dockerhub and quay.io is a Docker image (although I suppose quay technically can host rkt images as well, but I'm ignoring that fact for now).  So if everything is a Docker image, why call out Docker in the image name?  So I didn't-- hence "go-dev" as the image name, however...

None of that logic applies to Github.  A repository in Github isn't implicitly a Docker image as it is in Dockerhub.  It could be anything.  i.e. Prefixing "go-dev" with "docker", to me at least, wasn't redundant and also made it crystal clear that the repository was the source of the Dockerfile for the "go-dev" Docker image.

**Comment by mboersma** [comment]
> None of that logic applies to Github.

Good points all around. I don't feel that strongly about it, so that probably argues for leaving it as-is.

**Comment by krancour** [comment]
Let's leave this open, at least short term, until someone else weighs in.

**Comment by krancour** [comment]
No one else has sounded off on this.  I guess we can close?

**Comment by bacongobbler** [comment]
I tend to avoid bikeshedding arguments. It's a little confusing but idc all that much :)
