### ISSUE TITLE
gen-changelog.sh should also recognize doc( commits

### ISSUE THREAD

**Issue by bacongobbler** [deis/docker-go-dev#42]
Some users have used `doc(` instead of `docs(` in their commits. We should also throw those into the changelog, or alternatively enforce a new script across all repos to enforce the commit guidelines (not recommended).

related: https://github.com/deis/deisrel/pull/21

**Comment by krancour** [comment]
> or alternatively enforce a new script across all repos to enforce the commit guidelines (not recommended)

I liked it when we used a hook to do that for deis/deis.  The problem is that you need to opt into the hook-- which not all contributors will, which means mistakes like `doc(...)` vs `docs(...)` will still sneak in and won't always be noticed by reviewers since it's such a subtle difference.  There's that and _then_ the fact that we now have so many repos and contributors would need to opt in on _each_.

What if we could somehow build commit message verification into CI instead?  That would give us better guarantees.

**Comment by arschles** [comment]
Auto commit message verification seems like solving a problem that we don't have at scale.

Here's my proposal: (1) add a note to the contributing docs that well-formed commit messages are necessary so we can generate changelogs (and if you don't use the format, your work won't get credited) and (2) continue to check commit msgs on reviews

**Comment by bacongobbler** [comment]
> What if we could somehow build commit message verification into CI instead? That would give us better guarantees.

that's what I was proposing (though it's not really a problem we have right now).

> (1) add a note to the contributing docs that well-formed commit messages are necessary so we can generate changelogs (and if you don't use the format, your work won't get credited)

For sure. http://docs-v2.readthedocs.io/en/latest/contributing/submitting-a-pull-request/ should have some info to make that more clear that we grep the commit messages for generating the changelogs.

> and (2) continue to check commit msgs on reviews

sgtm.

Bringing the discussion back around, it sounds like option 1 is recommended (check for a `doc(` tag)?

**Comment by arschles** [comment]
checking for a `doc(` tag sgtm :+1:

**Comment by krancour** [comment]
> and if you don't use the format, your work won't get credited

A contributor not receiving the credit they deserve isn't the worst thing that can happen though.  The worst thing that can happen is that the changelog makes no mention of some contribution that many users would care to know about.

**Comment by mboersma** [comment]
`doc()` and `docs()` are now implemented in `deisrel changelog`.
